ifeq ($(CONFIG_LGE_COSMO_DRIVERS),y)
obj-y	+= muic/
obj-y	+= charger/
obj-y	+= fuel_gauge/
#obj-y	+= sound/
obj-y	+= subpmic/
# LGE_RAW_IP_START
obj-y	+= rindrv/
# LGE_RAW_IP_END
obj-y	+= misc/

#alexfed begin: 20101117 compile mtc ETA
obj-y   += mtc_eta/
#alexfed end: 20101117 compile mtc ETA

endif
